/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up users
         * @description Look up users by login or id, up to 100 in total; repeat `login` or `id` for several. Users Twitch does not know are left out.
         */
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/name-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the logins of a user
         * @description Every login the user was seen with in a logged chat, with the first and last time.
         */
        get: operations["getNameHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the logged channels
         * @description The channels being logged, ordered by login.
         */
        get: operations["getChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the chat badges of a channel
         * @description The global and the channel's Twitch chat badges, to render the `badges` tag of messages. Only for logged channels.
         */
        get: operations["getChatBadges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the streams of a year
         * @description The channel's streams in a year as SullyGnome knows them, from its cache when SullyGnome is unreachable.
         */
        get: operations["getStreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/log-dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the days with logs
         * @description The UTC days with messages in the channel, newest first.
         */
        get: operations["getChannelLogDates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the messages of a channel
         * @description The channel's messages in `[from, to)`.
         */
        get: operations["getChannelLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/logs/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a random message of a channel
         * @description One message picked at random.
         */
        get: operations["getRandomChannelMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the messages of a channel
         * @description The number of messages and the users with the most, optionally in `[from, to)`.
         */
        get: operations["getChannelStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/tiers/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rank the chatters of a period
         * @description Ranks the users by the number of 1, 5, 15, 30 and 60 minute windows they chatted in, during a calendar day, month or year in Europe/Moscow time.
         */
        get: operations["getTiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/users/{userId}/log-months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the months with logs of a user
         * @description The UTC months in which the user wrote in the channel, newest first.
         */
        get: operations["getUserLogMonths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/users/{userId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the messages of a user
         * @description The user's messages in the channel in `[from, to)`.
         */
        get: operations["getUserLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/users/{userId}/logs/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a random message of a user
         * @description One of the user's messages in the channel, picked at random.
         */
        get: operations["getRandomUserMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/users/{userId}/logs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the messages of a user
         * @description The user's messages in the channel that contain `q`, ignoring case.
         */
        get: operations["searchUserLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}/users/{userId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the messages of a user
         * @description The number of the user's messages in the channel, optionally in `[from, to)`.
         */
        get: operations["getUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opt-out-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an opt-out code
         * @description A one-time code for a chat command in a logged chat, valid for a minute: `!rustlog optout <code>` stops logging the sender and deletes their messages, `!rustlog optin <code>` logs them again. A broadcaster can hide their channel with `!rustlog optout-channel <code>` in its own chat, and show it again with `!rustlog optin-channel <code>`.
         */
        post: operations["createOptOutCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/channels/{channelId}/opt-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Opt a channel out
         * @description Stops logging the channel and hides its logs, which are kept. The bot stays in the chat, so that the broadcaster can opt back in there.
         */
        put: operations["optOutChannel"];
        post?: never;
        /**
         * Opt a channel back in
         * @description Logs the channel again and shows its logs, including those from before the opt-out.
         */
        delete: operations["optInChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/opt-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Opt a user out
         * @description Stops logging the user and deletes their messages and logins in every channel.
         */
        put: operations["optOutUser"];
        post?: never;
        /**
         * Opt a user back in
         * @description Logs the user again from now on; messages deleted by the opt-out stay deleted.
         */
        delete: operations["optInUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Start logging a channel
         * @description The bot joins the channel's chat.
         */
        put: operations["joinChannel"];
        post?: never;
        /**
         * Stop logging a channel
         * @description The bot leaves the channel's chat; its logs are kept.
         */
        delete: operations["leaveChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Users to look up; repeat a parameter for several. */
        UsersQuery: {
            /**
             * @description Twitch login.
             * @default []
             */
            login: string[];
            /**
             * @description Numeric Twitch id.
             * @default []
             */
            id: string[];
        };
        Users: {
            users: components["schemas"]["User"][];
        };
        User: {
            /**
             * @description A numeric Twitch user id, which channels have too.
             * @example 71092938
             */
            id: string;
            login: string;
        };
        ApiProblem: {
            /** @description A short summary of the code, for people. */
            title: string;
            /** @description What went wrong, for program logic. */
            code: components["schemas"]["ProblemCode"];
            /**
             * Format: uint16
             * @description The HTTP status code.
             */
            status: number;
            /** @description What exactly is wrong with this request, for people. */
            detail?: string | null;
        };
        /** @enum {string} */
        ProblemCode: "invalid_request" | "unauthorized" | "opted_out" | "not_found" | "method_not_allowed" | "upstream_unavailable" | "internal_error";
        UserPath: {
            /**
             * @description Id of the user.
             * @example 71092938
             */
            userId: string;
        };
        NameHistory: {
            names: components["schemas"]["PreviousName"][];
        };
        PreviousName: {
            login: string;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
        };
        Channels: {
            channels: components["schemas"]["User"][];
        };
        ChannelPath: {
            /**
             * @description Id of the channel.
             * @example 71092938
             */
            channelId: string;
        };
        ChatBadges: {
            badges: components["schemas"]["ChatBadge"][];
        };
        ChatBadge: {
            title: string;
            description: string;
            /** @description Badge set, such as `subscriber`. */
            setId: string;
            /**
             * @description Version within the set, such as `12`; together with the set it is
             *      the value of the IRC `badges` tag.
             */
            version: string;
            imageUrl1x: string;
            imageUrl2x: string;
        };
        StreamsQuery: {
            /**
             * Format: int32
             * @description Year of the streams.
             */
            year: number;
        };
        Streams: {
            /** @description The streams of the year, as SullyGnome knows them. */
            streams: components["schemas"]["Stream"][];
        };
        Stream: {
            /** @description SullyGnome's id of the stream. */
            id: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
            /** Format: uint32 */
            durationMinutes?: number | null;
            /** @description The games played, as SullyGnome lists them. */
            games?: string | null;
        };
        LogDates: {
            /** @description UTC days with messages, newest first. */
            dates: string[];
        };
        /** @description A required time range. */
        Range: {
            /**
             * Format: date-time
             * @description Start of the range, inclusive (RFC 3339).
             */
            from: string;
            /**
             * Format: date-time
             * @description End of the range, exclusive (RFC 3339).
             */
            to: string;
        };
        /** @description How messages are returned. */
        Format: {
            /** @description Response format; `basic-json` by default. */
            format?: components["schemas"]["LogFormat"];
        };
        LogFormat: "basic-json" | "full-json" | "ndjson" | "text" | "raw";
        /** @description Ordering and paging of a list of messages. */
        Paging: {
            /**
             * @description Newest messages first.
             * @default false
             */
            reverse: boolean;
            /**
             * Format: uint64
             * @description Return at most this many messages.
             */
            limit?: number | null;
            /**
             * Format: uint64
             * @description Skip this many messages first.
             */
            offset?: number | null;
        };
        /** @description The `basic-json` body; only for the documentation. */
        BasicMessages: {
            messages: components["schemas"]["BasicMessage"][];
        };
        BasicMessage: {
            text: string;
            displayName: string;
            /** Format: date-time */
            timestamp: string;
            id: string;
            tags: {
                [key: string]: string;
            };
        };
        /** @description The `full-json` body; only for the documentation. */
        FullMessages: {
            messages: components["schemas"]["FullMessage"][];
        };
        FullMessage: {
            /** Format: int8 */
            type: number;
            text: string;
            displayName: string;
            /** Format: date-time */
            timestamp: string;
            id: string;
            tags: {
                [key: string]: string;
            };
            username: string;
            channel: string;
            raw: string;
        };
        /** @description An optional time range: both ends or neither. */
        OptionalRange: {
            /**
             * Format: date-time
             * @description Start of the range, inclusive (RFC 3339). Requires `to`.
             */
            from?: string | null;
            /**
             * Format: date-time
             * @description End of the range, exclusive (RFC 3339). Requires `from`.
             */
            to?: string | null;
        };
        ChannelStats: {
            /** Format: uint64 */
            messageCount: number;
            /** @description The users with the most messages, most first. */
            topChatters: components["schemas"]["UserStats"][];
        };
        UserStats: {
            /**
             * @description A numeric Twitch user id, which channels have too.
             * @example 71092938
             */
            userId: string;
            /** @description Left out when Twitch does not know the user or cannot be asked. */
            login?: string | null;
            /** Format: uint64 */
            messageCount: number;
        };
        TiersPath: {
            /**
             * @description Id of the channel.
             * @example 71092938
             */
            channelId: string;
            /**
             * @description Calendar day, month or year in Europe/Moscow time.
             * @example 2026-03-01
             * @example 2026-03
             * @example 2026
             */
            period: string;
        };
        TiersQuery: {
            /**
             * @description Which messages count.
             * @default all
             */
            mode: components["schemas"]["TierMode"];
            /**
             * @description Bot logins to leave out, repeated for several. Replaces the default
             *      list of common bots; give it once empty to leave out none.
             * @default [
             *       "twirapp",
             *       "streamelements",
             *       "nightbot",
             *       "moobot",
             *       "mejkizbot",
             *       "supibot",
             *       "potatbotat",
             *       "fossabot"
             *     ]
             * @example [
             *       "twirapp",
             *       "streamelements",
             *       "nightbot",
             *       "moobot",
             *       "mejkizbot",
             *       "supibot",
             *       "potatbotat",
             *       "fossabot"
             *     ]
             */
            excludeBots: string[];
        };
        TierMode: "all" | "online" | "offline";
        TierTable: {
            /** @description The requested period. */
            period: string;
            /** @description Time zone of the period. */
            timezone: string;
            mode: components["schemas"]["TierMode"];
            /** Format: uint64 */
            totalUsers: number;
            /** Format: uint64 */
            totalMessages: number;
            /** Format: uint64 */
            totalUniqueMessages: number;
            /** @description Up to 500 users, the most active first. */
            entries: components["schemas"]["TierTableEntry"][];
        };
        TierTableEntry: {
            /**
             * @description A numeric Twitch user id, which channels have too.
             * @example 71092938
             */
            userId: string;
            /** @description Left out when Twitch does not know the user or cannot be asked. */
            login?: string | null;
            /** Format: uint64 */
            messages: number;
            /** Format: uint64 */
            uniqueMessages: number;
            /**
             * Format: uint32
             * @description Sum of the tier points over the window sizes.
             */
            tierScore: number;
            windows: components["schemas"]["Windows"];
        };
        /** @description Activity per window size. */
        Windows: {
            "1m": components["schemas"]["WindowActivity"];
            "5m": components["schemas"]["WindowActivity"];
            "15m": components["schemas"]["WindowActivity"];
            "30m": components["schemas"]["WindowActivity"];
            "60m": components["schemas"]["WindowActivity"];
        };
        WindowActivity: {
            /**
             * Format: uint64
             * @description Windows of this size with at least one message.
             */
            active: number;
            /**
             * Format: uint32
             * @description Rank among the users, from 1; left out when not ranked.
             */
            rank?: number | null;
            /** @description Tier of the rank; left out when not ranked. */
            tier?: string | null;
        };
        ChannelUserPath: {
            /**
             * @description Id of the channel.
             * @example 71092938
             */
            channelId: string;
            /**
             * @description Id of the user.
             * @example 71092938
             */
            userId: string;
        };
        LogMonths: {
            /** @description UTC months with messages as `YYYY-MM`, newest first. */
            months: string[];
        };
        SearchQuery: {
            /** @description Text to find in the messages, ignoring case. */
            q: string;
        };
        OptOutCode: {
            /**
             * @description Write `!rustlog optout <code>` in a logged chat to opt out, or one of
             *      `optin`, `optout-channel` and `optin-channel`.
             */
            code: string;
            /** Format: date-time */
            expiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUsers: {
        parameters: {
            query?: {
                /** @description Twitch login. */
                login?: string[];
                /** @description Numeric Twitch id. */
                id?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Users"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getNameHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NameHistory"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channels"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getChatBadges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatBadges"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getStreams: {
        parameters: {
            query: {
                /** @description Year of the streams. */
                year: number;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Streams"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getChannelLogDates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogDates"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getChannelLogs: {
        parameters: {
            query: {
                /** @description Start of the range, inclusive (RFC 3339). */
                from: string;
                /** @description End of the range, exclusive (RFC 3339). */
                to: string;
                /** @description Response format; `basic-json` by default. */
                format?: components["schemas"]["LogFormat"];
                /** @description Newest messages first. */
                reverse?: boolean;
                /** @description Return at most this many messages. */
                limit?: number | null;
                /** @description Skip this many messages first. */
                offset?: number | null;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages in the requested `format`: `basic-json` or `full-json` as JSON, `ndjson` as one basic message per line, `text` and `raw` as text lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicMessages"] | components["schemas"]["FullMessages"];
                    "application/x-ndjson": components["schemas"]["BasicMessage"];
                    "text/plain; charset=utf-8": string;
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getRandomChannelMessage: {
        parameters: {
            query?: {
                /** @description Response format; `basic-json` by default. */
                format?: components["schemas"]["LogFormat"];
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages in the requested `format`: `basic-json` or `full-json` as JSON, `ndjson` as one basic message per line, `text` and `raw` as text lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicMessages"] | components["schemas"]["FullMessages"];
                    "application/x-ndjson": components["schemas"]["BasicMessage"];
                    "text/plain; charset=utf-8": string;
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getChannelStats: {
        parameters: {
            query?: {
                /** @description Start of the range, inclusive (RFC 3339). Requires `to`. */
                from?: string | null;
                /** @description End of the range, exclusive (RFC 3339). Requires `from`. */
                to?: string | null;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelStats"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getTiers: {
        parameters: {
            query?: {
                /** @description Which messages count. */
                mode?: "all" | "online" | "offline";
                /**
                 * @description Bot logins to leave out, repeated for several. Replaces the default
                 *      list of common bots; give it once empty to leave out none.
                 */
                excludeBots?: string[];
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Calendar day, month or year in Europe/Moscow time. */
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierTable"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getUserLogMonths: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogMonths"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getUserLogs: {
        parameters: {
            query: {
                /** @description Start of the range, inclusive (RFC 3339). */
                from: string;
                /** @description End of the range, exclusive (RFC 3339). */
                to: string;
                /** @description Response format; `basic-json` by default. */
                format?: components["schemas"]["LogFormat"];
                /** @description Newest messages first. */
                reverse?: boolean;
                /** @description Return at most this many messages. */
                limit?: number | null;
                /** @description Skip this many messages first. */
                offset?: number | null;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages in the requested `format`: `basic-json` or `full-json` as JSON, `ndjson` as one basic message per line, `text` and `raw` as text lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicMessages"] | components["schemas"]["FullMessages"];
                    "application/x-ndjson": components["schemas"]["BasicMessage"];
                    "text/plain; charset=utf-8": string;
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getRandomUserMessage: {
        parameters: {
            query?: {
                /** @description Response format; `basic-json` by default. */
                format?: components["schemas"]["LogFormat"];
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages in the requested `format`: `basic-json` or `full-json` as JSON, `ndjson` as one basic message per line, `text` and `raw` as text lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicMessages"] | components["schemas"]["FullMessages"];
                    "application/x-ndjson": components["schemas"]["BasicMessage"];
                    "text/plain; charset=utf-8": string;
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    searchUserLogs: {
        parameters: {
            query: {
                /** @description Text to find in the messages, ignoring case. */
                q: string;
                /** @description Response format; `basic-json` by default. */
                format?: components["schemas"]["LogFormat"];
                /** @description Newest messages first. */
                reverse?: boolean;
                /** @description Return at most this many messages. */
                limit?: number | null;
                /** @description Skip this many messages first. */
                offset?: number | null;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The messages in the requested `format`: `basic-json` or `full-json` as JSON, `ndjson` as one basic message per line, `text` and `raw` as text lines. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicMessages"] | components["schemas"]["FullMessages"];
                    "application/x-ndjson": components["schemas"]["BasicMessage"];
                    "text/plain; charset=utf-8": string;
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    getUserStats: {
        parameters: {
            query?: {
                /** @description Start of the range, inclusive (RFC 3339). Requires `to`. */
                from?: string | null;
                /** @description End of the range, exclusive (RFC 3339). Requires `from`. */
                to?: string | null;
            };
            header?: never;
            path: {
                /** @description Id of the channel. */
                channelId: string;
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    createOptOutCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptOutCode"];
                };
            };
        };
    };
    optOutChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    optInChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    optOutUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    optInUser: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the user. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    joinChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    leaveChannel: {
        parameters: {
            query?: never;
            header: {
                /** @description The configured admin API key. */
                "X-Api-Key": string;
            };
            path: {
                /** @description Id of the channel. */
                channelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description no content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description Problem response */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
}
